<<<<<<< HEAD
export const UPDATE_STEP = "UPDATE_STEP";
export const UPDATE_STEP_SUCCESS = "UPDATE_STEP_SUCCESS";
export const INITIALIZE_USER_STATE = "INITIALIZE_USER_STATE";
=======
export const UPDATE_STEP = "UPDATE_STEP";
export const UPDATE_STEP_SUCCESS = "UPDATE_STEP_SUCCESS";
export const INITIALIZE_USER_STATE = "INITIALIZE_USER_STATE";
>>>>>>> ac9b403bd212644d3a86ebbf35eff29c408d9e87
